# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverctl', '0002_gameserver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='status',
            field=models.CharField(choices=[('LOADING', '起動中'), ('RUNNING', '作動中'), ('SAVING', '保存中'), ('STOPPING', '停止中')], default='STOPPING', max_length=12),
        ),
    ]
