# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serverctl', '0003_auto_20170325_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('INITIALIZING', '準備中'), ('LOADING', '起動中'), ('RUNNING', '作動中'), ('SAVING', '保存中'), ('STOPPING', '停止中')], max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='gameserver',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='status',
            field=models.CharField(choices=[('INITIALIZING', '準備中'), ('LOADING', '起動中'), ('RUNNING', '作動中'), ('SAVING', '保存中'), ('STOPPING', '停止中')], default='STOPPING', max_length=12),
        ),
        migrations.AddField(
            model_name='serverhistory',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverctl.GameServer'),
        ),
    ]
