# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serverctl', '0005_auto_20170326_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
