# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverctl', '0007_serverhistory_data_s3_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverhistory',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='gameserver',
            name='ip',
            field=models.CharField(default='', max_length=64),
        ),
    ]
