# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverctl', '0008_auto_20170412_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='current_id',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='gameserver',
            name='once_created',
            field=models.BooleanField(default=False),
        ),
    ]
