version: '2'
services:
  postgres:
    restart: always
    image: postgres:latest
    env_file: .env

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file: .env
